# Generated by Django 3.2.6 on 2021-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_price', models.CharField(blank=True, max_length=50, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product')),
            ],
        ),
    ]
